version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - echo Running tests 
            - dotnet test --logger "trx;LogFileName=TestResults.trx" --results-directory ./testresults
        
reports:
    arn:aws:kms:us-east-2:958862843347:alias/aws/s3:
    files:
        - '**/*'
    base-directory:
        - './testresults'
    discard-paths: false #do not remove file paths from test result files