version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - echo Running tests 
            - dotnet test --logger "trx;LogFileName=TestResults.trx" --results-directory ./testresults